using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace ManageHospitalData.Migrations.Scripts
{
    [DbContext(typeof(ManageHospitalDBContext))]
    [Migration("20220128192026_RegionAndCitiesMigration")]
    public partial class RegionAndCitiesMigration : Migration
    {
        //private const string MIGRATION_SQL_SCRIPT_FILE_NAME = @"Migrations\Scripts\RegionAndCities.sql";
        //private const string MIGRATION_SQL_SCRIPT_FILE_NAME = @"Scripts\RegionAndCities.sql";

        protected override void Up(MigrationBuilder migrationBuilder)
        {
            ////string sql = Path.Combine(Directory.GetParent(Directory.GetCurrentDirectory()).FullName, MIGRATION_SQL_SCRIPT_FILE_NAME);
            //string sql = Path.Combine(MIGRATION_SQL_SCRIPT_FILE_NAME);
            //migrationBuilder.Sql(File.ReadAllText(sql));
            migrationBuilder.Sql(regions);
            migrationBuilder.Sql(cities);
        }

        #region Regions
        readonly string regions = "INSERT INTO regions(Id,Name) VALUES"
                               + "(1,'Tanger-Tétouan-Al Hoceïma'),"
                               + "(2,'l Oriental'),"
                               + "(3,'Fès-Meknès'),"
                               + "(4,'Rabat-Salé-Kénitra'),"
                               + "(5,'Béni Mellal-Khénifra'),"
                               + "(6,'Casablanca-Settat'),"
                               + "(7,'Marrakech-Safi'),"
                               + "(8,'Drâa-Tafilalet'),"
                               + "(9,'Souss-Massa'),"
                               + "(10,'Guelmim-Oued Noun'),"
                               + "(11,'Laâyoune-Sakia El Hamra'),"
                               + "(12,'Dakhla-Oued Ed Dahab')";
        #endregion
        #region cities
        readonly string cities = "INSERT INTO cities(Name,RegionId) VALUES"
                               + "('Aïn Harrouda',6),"
                               + "('Ben Yakhlef',6),"
                               + "('Bouskoura',6),"
                               + "('Casablanca',6),"
                               + "('Médiouna',6),"
                               + "('Mohammadia',6),"
                               + "('Tit Mellil',6),"
                               + "('Ben Yakhlef',6),"
                               + "('Bejaâd', 5),"
                               + "('Ben Ahmed',6),"
                               + "('Benslimane',6),"
                               + "('Berrechid',6),"
                               + "('Boujniba', 5),"
                               + "('Boulanouare', 5),"
                               + "('Bouznika',6),"
                               + "('Deroua',6),"
                               + "('El Borouj',6),"
                               + "('El Gara',6),"
                               + "('Guisser',6),"
                               + "('Hattane', 5),"
                               + "('Khouribga', 5),"
                               + "('Loulad',6),"
                               + "('Oued Zem', 5),"
                               + "('Oulad Abbou',6),"
                               + "('Oulad H''Riz Sahel',6),"
                               + "('Oulad M''rah',6),"
                               + "('Oulad Saïd',6),"
                               + "('Oulad Sidi Ben Daoud',6),"
                               + "('Ras El Aïn',6),"
                               + "('Settat',6),"
                               + "('Sidi Rahhal Chataï',6),"
                               + "('Soualem',6),"
                               + "('Azemmour',6),"
                               + "('Bir Jdid',6),"
                               + "('Bouguedra', 7),"
                               + "('Echemmaia', 7),"
                               + "('El Jadida',6),"
                               + "('Hrara', 7),"
                               + "('Ighoud', 7),"
                               + "('Jamâat Shaim', 7),"
                               + "('Jorf Lasfar',6),"
                               + "('Khemis Zemamra',6),"
                               + "('Laaounate',6),"
                               + "('Moulay Abdallah',6),"
                               + "('Oualidia',6),"
                               + "('Oulad Amrane',6),"
                               + "('Oulad Frej',6),"
                               + "('Oulad Ghadbane',6),"
                               + "('Safi', 7),"
                               + "('Sebt El Maârif',6),"
                               + "('Sebt Gzoula', 7),"
                               + "('Sidi Ahmed', 7),"
                               + "('Sidi Ali Ban Hamdouche',6),"
                               + "('Sidi Bennour',6),"
                               + "('Sidi Bouzid',6),"
                               + "('Sidi Smaïl',6),"
                               + "('Youssoufia', 7),"
                               + "('Fès', 3),"
                               + "('Aïn Cheggag', 3),"
                               + "('Bhalil', 3),"
                               + "('Boulemane', 3),"
                               + "('El Menzel', 3),"
                               + "('Guigou', 3),"
                               + "('Imouzzer Kandar', 3),"
                               + "('Imouzzer Marmoucha', 3),"
                               + "('Missour', 3),"
                               + "('Moulay Yaâcoub', 3),"
                               + "('Ouled Tayeb', 3),"
                               + "('Outat El Haj', 3),"
                               + "('Ribate El Kheir', 3),"
                               + "('Séfrou', 3),"
                               + "('Skhinate', 3),"
                               + "('Tafajight', 3),"
                               + "('Arbaoua', 4),"
                               + "('Aïn Dorij', 1),"
                               + "('Dar Gueddari', 4),"
                               + "('Had Kourt', 4),"
                               + "('Jorf El Melha', 4),"
                               + "('Kénitra', 4),"
                               + "('Khenichet', 4),"
                               + "('Lalla Mimouna', 4),"
                               + "('Mechra Bel Ksiri', 4),"
                               + "('Mehdia', 4),"
                               + "('Moulay Bousselham', 4),"
                               + "('Sidi Allal Tazi', 4),"
                               + "('Sidi Kacem', 4),"
                               + "('Sidi Slimane', 4),"
                               + "('Sidi Taibi', 4),"
                               + "('Sidi Yahya El Gharb', 4),"
                               + "('Souk El Arbaa', 4),"
                               + "('Akka', 9),"
                               + "('Assa', 10),"
                               + "('Bouizakarne', 10),"
                               + "('El Ouatia', 10),"
                               + "('Es-Semara', 11),"
                               + "('Fam El Hisn', 9),"
                               + "('Foum Zguid', 9),"
                               + "('Guelmim', 10),"
                               + "('Taghjijt', 10),"
                               + "('Tan-Tan', 10),"
                               + "('Tata', 9),"
                               + "('Zag', 10),"
                               + "('Marrakech', 7),"
                               + "('Ait Daoud', 7),"
                               + "('Amizmiz', 7),"
                               + "('Assahrij', 7),"
                               + "('Aït Ourir', 7),"
                               + "('Ben Guerir', 7),"
                               + "('Chichaoua', 7),"
                               + "('El Hanchane', 7),"
                               + "('El Kelaâ des Sraghna', 7),"
                               + "('Essaouira', 7),"
                               + "('Fraïta', 7),"
                               + "('Ghmate', 7),"
                               + "('Ighounane', 8),"
                               + "('Imintanoute', 7),"
                               + "('Kattara', 7),"
                               + "('Lalla Takerkoust', 7),"
                               + "('Loudaya', 7),"
                               + "('Lâattaouia', 7),"
                               + "('Moulay Brahim', 7),"
                               + "('Mzouda', 7),"
                               + "('Ounagha', 7),"
                               + "('Sid L''Mokhtar', 7),"
                               + "('Sid Zouin', 7),"
                               + "('Sidi Abdallah Ghiat', 7),"
                               + "('Sidi Bou Othmane', 7),"
                               + "('Sidi Rahhal', 7),"
                               + "('Skhour Rehamna', 7),"
                               + "('Smimou', 7),"
                               + "('Tafetachte', 7),"
                               + "('Tahannaout', 7),"
                               + "('Talmest', 7),"
                               + "('Tamallalt', 7),"
                               + "('Tamanar', 7),"
                               + "('Tamansourt', 7),"
                               + "('Tameslouht', 7),"
                               + "('Tanalt', 9),"
                               + "('Zeubelemok', 7),"
                               + "('Meknès‎', 3),"
                               + "('Khénifra', 5),"
                               + "('Agourai', 3),"
                               + "('Ain Taoujdate', 3),"
                               + "('MyAliCherif', 8),"
                               + "('Rissani', 8),"
                               + "('Amalou Ighriben', 5),"
                               + "('Aoufous', 8),"
                               + "('Arfoud', 8),"
                               + "('Azrou', 3),"
                               + "('Aïn Jemaa', 3),"
                               + "('Aïn Karma', 3),"
                               + "('Aïn Leuh', 3),"
                               + "('Aït Boubidmane', 3),"
                               + "('Aït Ishaq', 5),"
                               + "('Boudnib', 8),"
                               + "('Boufakrane', 3),"
                               + "('Boumia', 8),"
                               + "('El Hajeb', 3),"
                               + "('Elkbab', 5),"
                               + "('Er-Rich', 5),"
                               + "('Errachidia', 8),"
                               + "('Gardmit', 8),"
                               + "('Goulmima', 8),"
                               + "('Gourrama', 8),"
                               + "('Had Bouhssoussen', 5),"
                               + "('Haj Kaddour', 3),"
                               + "('Ifrane', 3),"
                               + "('Itzer', 8),"
                               + "('Jorf', 8),"
                               + "('Kehf Nsour', 5),"
                               + "('Kerrouchen', 5),"
                               + "('M''haya', 3),"
                               + "('M''rirt', 5),"
                               + "('Midelt', 8),"
                               + "('Moulay Ali Cherif', 8),"
                               + "('Moulay Bouazza', 5),"
                               + "('Moulay Idriss Zerhoun', 3),"
                               + "('Moussaoua', 3),"
                               + "('N''Zalat Bni Amar', 3),"
                               + "('Ouaoumana', 5),"
                               + "('Oued Ifrane', 3),"
                               + "('Sabaa Aiyoun', 3),"
                               + "('Sebt Jahjouh', 3),"
                               + "('Sidi Addi', 3),"
                               + "('Tichoute', 8),"
                               + "('Tighassaline', 5),"
                               + "('Tighza', 5),"
                               + "('Timahdite', 3),"
                               + "('Tinejdad', 8),"
                               + "('Tizguite', 3),"
                               + "('Toulal', 3),"
                               + "('Tounfite', 8),"
                               + "('Zaouia d''Ifrane', 3),"
                               + "('Zaïda', 8),"
                               + "('Ahfir', 2),"
                               + "('Aklim', 2),"
                               + "('Al Aroui', 2),"
                               + "('Aïn Bni Mathar', 2),"
                               + "('Aïn Erreggada', 2),"
                               + "('Ben Taïeb', 2),"
                               + "('Berkane', 2),"
                               + "('Bni Ansar', 2),"
                               + "('Bni Chiker', 2),"
                               + "('Bni Drar', 2),"
                               + "('Bni Tadjite', 2),"
                               + "('Bouanane', 2),"
                               + "('Bouarfa', 2),"
                               + "('Bouhdila', 2),"
                               + "('Dar El Kebdani', 2),"
                               + "('Debdou', 2),"
                               + "('Douar Kannine', 2),"
                               + "('Driouch', 2),"
                               + "('El Aïoun Sidi Mellouk', 2),"
                               + "('Farkhana', 2),"
                               + "('Figuig', 2),"
                               + "('Ihddaden', 2),"
                               + "('Jaâdar', 2),"
                               + "('Jerada', 2),"
                               + "('Kariat Arekmane', 2),"
                               + "('Kassita', 2),"
                               + "('Kerouna', 2),"
                               + "('Laâtamna', 2),"
                               + "('Madagh', 2),"
                               + "('Midar', 2),"
                               + "('Nador', 2),"
                               + "('Naima', 2),"
                               + "('Oued Heimer', 2),"
                               + "('Oujda', 2),"
                               + "('Ras El Ma', 2),"
                               + "('Saïdia', 2),"
                               + "('Selouane', 2),"
                               + "('Sidi Boubker', 2),"
                               + "('Sidi Slimane Echcharaa', 2),"
                               + "('Talsint', 2),"
                               + "('Taourirt', 2),"
                               + "('Tendrara', 2),"
                               + "('Tiztoutine', 2),"
                               + "('Touima', 2),"
                               + "('Touissit', 2),"
                               + "('Zaïo', 2),"
                               + "('Zeghanghane', 2),"
                               + "('Rabat', 4),"
                               + "('Salé', 4),"
                               + "('Ain El Aouda', 4),"
                               + "('Harhoura', 4),"
                               + "('Khémisset', 4),"
                               + "('Oulmès', 4),"
                               + "('Rommani', 4),"
                               + "('Sidi Allal El Bahraoui', 4),"
                               + "('Sidi Bouknadel', 4),"
                               + "('Skhirate', 4),"
                               + "('Tamesna', 4),"
                               + "('Témara', 4),"
                               + "('Tiddas', 4),"
                               + "('Tiflet', 4),"
                               + "('Touarga', 4),"
                               + "('Agadir', 9),"
                               + "('Agdz', 8),"
                               + "('Agni Izimmer', 9),"
                               + "('Aït Melloul', 9),"
                               + "('Alnif', 8),"
                               + "('Anzi', 9),"
                               + "('Aoulouz', 9),"
                               + "('Aourir', 9),"
                               + "('Arazane', 9),"
                               + "('Aït Baha', 9),"
                               + "('Aït Iaâza', 9),"
                               + "('Aït Yalla', 8),"
                               + "('Ben Sergao', 9),"
                               + "('Biougra', 9),"
                               + "('Boumalne-Dadès', 8),"
                               + "('Dcheira El Jihadia', 9),"
                               + "('Drargua', 9),"
                               + "('El Guerdane', 9),"
                               + "('Harte Lyamine', 8),"
                               + "('Ida Ougnidif', 9),"
                               + "('Ifri', 8),"
                               + "('Igdamen', 9),"
                               + "('Ighil n''Oumgoun', 8),"
                               + "('Imassine', 8),"
                               + "('Inezgane', 9),"
                               + "('Irherm', 9),"
                               + "('Kelaat-M''Gouna', 8),"
                               + "('Lakhsas', 9),"
                               + "('Lakhsass', 9),"
                               + "('Lqliâa', 9),"
                               + "('M''semrir', 8),"
                               + "('Massa (Maroc)', 9),"
                               + "('Megousse', 9),"
                               + "('Ouarzazate', 8),"
                               + "('Oulad Berhil', 9),"
                               + "('Oulad Teïma', 9),"
                               + "('Sarghine', 8),"
                               + "('Sidi Ifni', 10),"
                               + "('Skoura', 8),"
                               + "('Tabounte', 8),"
                               + "('Tafraout', 9),"
                               + "('Taghzout', 1),"
                               + "('Tagzen', 9),"
                               + "('Taliouine', 9),"
                               + "('Tamegroute', 8),"
                               + "('Tamraght', 9),"
                               + "('Tanoumrite Nkob Zagora', 8),"
                               + "('Taourirt ait zaghar', 8),"
                               + "('Taroudannt', 9),"
                               + "('Temsia', 9),"
                               + "('Tifnit', 9),"
                               + "('Tisgdal', 9),"
                               + "('Tiznit', 9),"
                               + "('Toundoute', 8),"
                               + "('Zagora', 8),"
                               + "('Afourar', 5),"
                               + "('Aghbala', 5),"
                               + "('Azilal', 5),"
                               + "('Aït Majden', 5),"
                               + "('Beni Ayat', 5),"
                               + "('Béni Mellal', 5),"
                               + "('Bin elouidane', 5),"
                               + "('Bradia', 5),"
                               + "('Bzou', 5),"
                               + "('Dar Oulad Zidouh', 5),"
                               + "('Demnate', 5),"
                               + "('Dra''a', 8),"
                               + "('El Ksiba', 5),"
                               + "('Foum Jamaa', 5),"
                               + "('Fquih Ben Salah', 5),"
                               + "('Kasba Tadla', 5),"
                               + "('Ouaouizeght', 5),"
                               + "('Oulad Ayad', 5),"
                               + "('Oulad M''Barek', 5),"
                               + "('Oulad Yaich', 5),"
                               + "('Sidi Jaber', 5),"
                               + "('Souk Sebt Oulad Nemma', 5),"
                               + "('Zaouïat Cheikh', 5),"
                               + "('Tanger‎', 1),"
                               + "('Tétouan‎', 1),"
                               + "('Akchour', 1),"
                               + "('Assilah', 1),"
                               + "('Bab Berred', 1),"
                               + "('Bab Taza', 1),"
                               + "('Brikcha', 1),"
                               + "('Chefchaouen', 1),"
                               + "('Dar Bni Karrich', 1),"
                               + "('Dar Chaoui', 1),"
                               + "('Fnideq', 1),"
                               + "('Gueznaia', 1),"
                               + "('Jebha', 1),"
                               + "('Karia', 3),"
                               + "('Khémis Sahel', 1),"
                               + "('Ksar El Kébir', 1),"
                               + "('Larache', 1),"
                               + "('M''diq', 1),"
                               + "('Martil', 1),"
                               + "('Moqrisset', 1),"
                               + "('Oued Laou', 1),"
                               + "('Oued Rmel', 1),"
                               + "('Ouazzane', 1),"
                               + "('Point Cires', 1),"
                               + "('Sidi Lyamani', 1),"
                               + "('Sidi Mohamed ben Abdallah el-Raisuni', 1),"
                               + "('Zinat', 1),"
                               + "('Ajdir‎', 1),"
                               + "('Aknoul‎', 3),"
                               + "('Al Hoceïma‎', 1),"
                               + "('Aït Hichem‎', 1),"
                               + "('Bni Bouayach‎', 1),"
                               + "('Bni Hadifa‎', 1),"
                               + "('Ghafsai‎', 3),"
                               + "('Guercif‎', 2),"
                               + "('Imzouren‎', 1),"
                               + "('Inahnahen‎', 1),"
                               + "('Issaguen (Ketama)‎', 1),"
                               + "('Karia (El Jadida)‎',6),"
                               + "('Karia Ba Mohamed‎', 3),"
                               + "('Oued Amlil‎', 3),"
                               + "('Oulad Zbair‎', 3),"
                               + "('Tahla‎', 3),"
                               + "('Tala Tazegwaght‎', 1),"
                               + "('Tamassint‎', 1),"
                               + "('Taounate‎', 3),"
                               + "('Targuist‎', 1),"
                               + "('Taza‎', 3),"
                               + "('Taïnaste‎', 3),"
                               + "('Thar Es-Souk‎', 3),"
                               + "('Tissa‎', 3),"
                               + "('Tizi Ouasli‎', 3),"
                               + "('Laayoune‎', 11),"
                               + "('El Marsa‎', 11),"
                               + "('Tarfaya‎', 11),"
                               + "('Boujdour‎', 11),"
                               + "('Awsard', 12),"
                               + "('Oued-Eddahab', 12),"
                               + "('Stehat', 1),"
                               + "('Aït Attab', 5);";
        #endregion

    }
}
